# Generated by Django 6.1 on 2026-08-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_expense_expensesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='kind',
            field=models.CharField(choices=[('expense', 'Expense'), ('payment', 'Payment')], default='expense', max_length=10),
        ),
    ]
