# Generated by Django 5.1.7 on 2026-09-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_expense_split_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='kind',
            field=models.CharField(choices=[('expense', 'Expense'), ('payment', 'Payment'), ('refund', 'Refund')], default='expense', max_length=10),
        ),
    ]
