# Generated by Django 5.1.7 on 2026-09-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_expense_is_refunded_alter_expense_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact amounts'), ('percent', 'Percentages'), ('shares', 'Shares')], default='equal', max_length=10),
        ),
    ]
