# Generated by Django 5.1.7 on 2026-09-02 23:40

import groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_expense_split_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default=groups.models.generate_code, max_length=8, unique=True),
        ),
    ]
