# Generated by Django 5.1.7 on 2026-08-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_simplify_debts_alter_activitylog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact amounts'), ('percent', 'Percentages')], default='equal', max_length=10),
        ),
    ]
